### ISSUE TITLE
Licence for LeanbackLauncher

### ISSUE THREAD

**Issue by mew22** [rockon999/rockon999.github.io#1]
Hi,
I post my comment here because there is no possibilities on the repository https://github.com/rockon999/LeanbackLauncher.
What is the licence of your leanbacklauncher?

BR,
Sebastien

**Comment by rockon999** [comment]
I've clarified the licensing. Essentially, because I utilize decompiled sources I don't make any licensing claims or claims of ownership over them.

**Comment by mew22** [comment]
Thanks :)
